### ISSUE TITLE
Blocking all notifications from certain group chats

### ISSUE THREAD

**Issue by bilogic** [LukasLen/Privacy-Extension-For-WhatsApp-Web#14]
Hi,

I just got to know about whatsapp web chrome extensions and found yours.

So I'm not sure if this is a valid feature request, but I like to ask if it is possible to block all notifications from certain group chats via an extension? I'm new to this and don't really know the mechanics and/or limitations.

Thank you!

**Comment by LukasLen** [comment]
Interesting proposal, however, while technically possible, this feature does not fit with the premise of this extension.

I'm not totally sure if you already know about the WhatsApp feature to mute certain chats/group chats: [https://faq.whatsapp.com/web/chats/how-to-manage-your-notifications](https://faq.whatsapp.com/web/chats/how-to-manage-your-notifications) - could be that this already satisfies your request.

Thank you for your suggestion and the time you took to create this issue. I will close it due to the above.
